export const API = 'API';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const GET_TOKEN = 'GET_TOKEN';

export const GET_COMPANY_LIST = 'GET_COMPANY_LIST';
export const GET_CITIES_LIST = 'GET_CITIES_LIST';
export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_CONTRACTS_LIST = 'GET_CONTRACTS_LIST';
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_VENDOR_LIST = 'GET_VENDOR_LIST';
export const GET_COST_CENTERS_LIST = 'GET_COST_CENTERS_LIST';
export const GET_DEPARTMENT_LIST = 'GET_DEPARTMENT_LIST';

export const GET_ONE_COMPANY = 'GET_ONE_COMPANY';
export const GET_ONE_CONTRACT = 'GET_ONE_CONTRACT';
export const GET_ONE_VENDOR = 'GET_ONE_VENDOR';
export const GET_ONE_DEPARTMENT = 'GET_ONE_DEPARTMENT';

export const POST_NEW_COMPANY = 'POST_NEW_COMPANY';
export const POST_NEW_VENDOR = 'POST_NEW_VENDOR';
export const POST_NEW_CONTRACT = 'POST_NEW_CONTRACT';
export const POST_NEW_COST_CENTER = 'POST_NEW_COST_CENTER';
export const POST_NEW_DEPARTMENT = 'POST_NEW_DEPARTMENT';

export const PUT_COMPANY = 'PUT_COMPANY';
export const PUT_VENDOR = 'PUT_VENDOR';
export const PUT_DEPARTMENT = 'PUT_DEPARTMENT';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_VENDOR = 'DELETE_VENDOR';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
