export const API = 'API';
export const SUCCESS = '_SUCCESS';
export const FAIL = '_FAIL';

export const GET_TOKEN = 'GET_TOKEN';

export const GET_COMPANY_LIST = 'GET_COMPANY_LIST';
export const GET_CITIES_LIST = 'GET_CITIES_LIST';
export const GET_COUNTRIES_LIST = 'GET_COUNTRIES_LIST';
export const GET_CONTRACTS_LIST = 'GET_CONTRACTS_LIST';
export const GET_CURRENCY_LIST = 'GET_CURRENCY_LIST';
export const GET_TITLE_LIST = 'GET_TITLE_LIST';
export const GET_VENDOR_LIST = 'GET_VENDOR_LIST';
export const GET_COST_CENTERS_LIST = 'GET_COST_CENTERS_LIST';
export const GET_DEPARTMENT_LIST = 'GET_DEPARTMENT_LIST';
export const GET_SITE_LIST = 'GET_SITE_LIST';
export const GET_CHECK_FACTORS_LIST = 'GET_CHECK_FACTORS_LIST';
export const GET_EXIT_TYPES_LIST = 'GET_EXIT_TYPES_LIST';

export const GET_ONE_COMPANY = 'GET_ONE_COMPANY';
export const GET_ONE_CONTRACT = 'GET_ONE_CONTRACT';
export const GET_ONE_VENDOR = 'GET_ONE_VENDOR';
export const GET_ONE_TITLE = 'GET_ONE_TITLE';
export const GET_ONE_DEPARTMENT = 'GET_ONE_DEPARTMENT';
export const GET_ONE_SITE = 'GET_ONE_SITE';
export const GET_ONE_COST_CENTER = 'GET_ONE_COST_CENTER';
export const GET_ONE_CHECK_FACTORY = 'GET_ONE_CHECK_FACTORY';
export const GET_ONE_EXIT_TYPE = 'GET_ONE_EXIT_TYPE';

export const POST_NEW_COMPANY = 'POST_NEW_COMPANY';
export const POST_NEW_VENDOR = 'POST_NEW_VENDOR';
export const POST_NEW_CONTRACT = 'POST_NEW_CONTRACT';
export const POST_NEW_TITLE = 'POST_NEW_TITLE';
export const POST_NEW_COST_CENTER = 'POST_NEW_COST_CENTER';
export const POST_NEW_DEPARTMENT = 'POST_NEW_DEPARTMENT';
export const POST_NEW_CHECK_FACTOR = 'POST_NEW_CHECK_FACTOR';
export const POST_NEW_SITE = 'POST_NEW_SITE';
export const POST_NEW_EXIT_TYPE = 'POST_NEW_EXIT_TYPE';

export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_SITE = 'UPDATE_SITE';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_VENDOR = 'UPDATE_VENDOR';
export const UPDATE_COST_CENTER = 'UPDATE_COST_CENTER';
export const UPDATE_CHECK_FACTORY = 'UPDATE_CHECK_FACTORY';
export const UPDATE_EXIT_TYPE = 'UPDATE_EXIT_TYPE';

export const DELETE_COMPANY = 'DELETE_COMPANY';
export const DELETE_VENDOR = 'DELETE_VENDOR';
export const DELETE_TITLE = 'DELETE_TITLE';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
export const DELETE_SITE = 'DELETE_SITE';
export const DELETE_COST_CENTER = 'DELETE_COST_CENTER';
export const DELETE_CHECK_FACTORY = 'DELETE_CHECK_FACTORY';
export const DELETE_EXIT_TYPE = 'DELETE_EXIT_TYPE';

export const CHANGE_PARENT_FOR_DEPARTMENTS = 'CHANGE_PARENT_FOR_DEPARTMENTS';
